import streamlit as st

def app():

    st.title('Gallery entrance')

    st.text('')

    
    st.text('This page aims to showcase the results obtained by\ntraining a dcGAN neural network, adapted from Keras.')
    st.text('The input given was a dataset from Kaggle which\nincluded some of the most important artists in history.\nDifferent models were generated by feeding them\nimages of different artist within certain styles.')
    st.text('Due to the varied nature of the data set,\nthere was not a very defined result in the images obtained;\nthis was somewhat expected as these models are often fed very similar\nlooking data')
    st.text("However, some interesting patterns did emerge,\nand they can be seen on the different tabs.")
    st.text('')
    st.text("Go ahead, and explore the gallery's different sections")